apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: yinglu91/k-webapp:3.0
        env:
        - name: DB_URL
          value: postgresql://localhost:5432
        ports:
        - containerPort: 8080
        